import {
  Analytics,
  Home,
  Images,
  Integrations,
  Inventory,
  Marketing,
  Organization,
  ThreeD,
  Video,
  VirtualStudio,
  Website,
} from '@spyne-console/design-system/icons';

export const menuItems = [
  {
    id: 'home',
    label: 'Home',
    icon: <Home className="stroke-typography-100 h-4 w-4" />,
    slug: '/home',
    hidden: false,
    permissions: [],
  },
  {
    id: 'virtual-studio',
    label: 'Virtual Studio',
    icon: <VirtualStudio className="stroke-typography-100 h-4 w-4" />,
    slug: '/common-virtual-studio',
    hidden: false,
    permissions: [],
    subMenu: [
      {
        id: 'images',
        label: 'Images',
        icon: <Images className="stroke-typography-100 h-4 w-4" />,
        slug: '/virtual-studio/images',
        hidden: false,
        permissions: [],
      },
      {
        id: '360-spin',
        label: '360° Spin',
        icon: <ThreeD className="stroke-typography-100 h-4 w-4" />,
        slug: '/virtual-studio/360-spin',
        hidden: false,
        permissions: [],
      },
      {
        id: 'video-tour',
        label: 'Video Tour',
        icon: <Video className="stroke-typography-100 h-4 w-4" />,
        slug: '/virtual-studio/video-tour',
        hidden: false,
        permissions: [],
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: <Inventory className="stroke-typography-100 h-4 w-4" />,
    slug: null,
    hidden: false,
    permissions: [],
    subMenu: [
      {
        id: 'listing',
        label: 'Listing',
        icon: '/icons/listing.svg',
        slug: '/inventory/listings',
        hidden: false,
        permissions: [],
      },
      {
        id: 'media',
        label: 'Media',
        icon: '/icons/media.svg',
        slug: '/inventory/media',
        hidden: false,
        permissions: [],
      },
      {
        id: 'sourcing',
        label: 'Sourcing',
        icon: '/icons/sourcing.svg',
        slug: '/inventory/sourcing',
        hidden: false,
        permissions: [],
      },
    ],
  },
  {
    id: 'website-builder',
    label: 'Website Builder',
    icon: <Website className="stroke-typography-100 h-4 w-4" />,
    slug: '/dealer-websites',
    hidden: false,
    permissions: [],
    subMenu: [
      {
        id: 'templates',
        label: 'Templates',
        icon: '/icons/templates.svg',
        slug: '/website-builder/templates',
        hidden: false,
        permissions: [],
      },
      {
        id: 'landing-page',
        label: 'Landing Page',
        icon: '/icons/landing.svg',
        slug: '/website-builder/landing-page',
        hidden: false,
        permissions: [],
      },
      {
        id: 'list-page',
        label: 'List Page',
        icon: '/icons/list.svg',
        slug: '/website-builder/list-page',
        hidden: false,
        permissions: [],
      },
      {
        id: 'details-page',
        label: 'Details Page',
        icon: '/icons/details.svg',
        slug: '/website-builder/details-page',
        hidden: false,
        permissions: [],
      },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    icon: <Marketing className="stroke-typography-100 h-4 w-4" />,
    slug: '/marketing',
    hidden: false,
    permissions: [],
    subMenu: [
      {
        id: 'google-vehicle-listing',
        label: 'Google Vehicle Listing',
        icon: '/icons/google.svg',
        slug: '/marketing/google-vehicle-listing',
        hidden: false,
        permissions: [],
      },
      {
        id: 'facebook-ads',
        label: 'Facebook Ads',
        icon: '/icons/facebook.svg',
        slug: '/marketing/facebook-ads',
        hidden: false,
        permissions: [],
      },
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: <Analytics className="stroke-typography-100 h-4 w-4" />,
    slug: '/analytics',
    hidden: false,
    permissions: [],
  },
  {
    id: 'developer-hub',
    label: 'Developer Hub',
    // icon: <Developer className="w-4 h-4 stroke-typography-100" />,
    slug: '/developer-hub',
    hidden: false,
    permissions: [],
  },
  {
    id: 'integrations',
    label: 'Integrations',
    icon: <Integrations className="stroke-typography-100 h-4 w-4" />,
    slug: '/integrations',
    hidden: false,
    permissions: [],
  },
  {
    id: 'organization',
    label: 'Organization',
    icon: null,
    slug: '/organization',
    hidden: false,
    permissions: [],
  },
];
